---

- hosts: all
  remote_user: ec2-user
  become: true
  tasks:

  - name: install apache2 package
    yum:
      name: httpd
      state: latest
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  - name: add php support for apache
    yum: 
      name: php
      state: latest
