---

- hosts: all
  remote_user: ec2-user
  become: true
  tasks:

  - name: uninstall apache2 package
    yum:
      name: httpd
      state: absent
  - name: remove php support for apache
    yum: 
      name: php
      state: absent
